// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  ProductTypeElement,
  BinaryWriter,
  BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";

export type SetReady = {
  code: string,
  ready: boolean,
};

export namespace SetReady {
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("code", AlgebraicType.createStringType()),
      new ProductTypeElement("ready", AlgebraicType.createBoolType()),
    ]);
  }
  export function serialize(writer: BinaryWriter, value: SetReady): void {
    SetReady.getTypeScriptAlgebraicType().serialize(writer, value);
  }
  export function deserialize(reader: BinaryReader): SetReady {
    return SetReady.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
